// <auto-generated />
using System;
using Hair_Salon_Web_ASP.NET.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hair_Salon_Web_ASP.NET.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240521150032_Ver21052024")]
    partial class Ver21052024
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Hair_Salon_Web_ASP.NET.Models.Appointment", b =>
                {
                    b.Property<int>("app_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("booking_time")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("emp_id_chosen")
                        .HasColumnType("int");

                    b.Property<string>("finish_time")
                        .HasColumnType("longtext");

                    b.Property<int>("ser_id")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .HasColumnType("longtext");

                    b.Property<int?>("user_id_book")
                        .HasColumnType("int");

                    b.HasKey("app_id");

                    b.HasIndex("emp_id_chosen");

                    b.HasIndex("ser_id");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Hair_Salon_Web_ASP.NET.Models.Post", b =>
                {
                    b.Property<int>("post_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<string>("post_image")
                        .HasColumnType("longtext");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("post_id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Hair_Salon_Web_ASP.NET.Models.Service", b =>
                {
                    b.Property<int>("ser_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("price")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ser_image")
                        .HasColumnType("longtext");

                    b.Property<int>("time_to_cut")
                        .HasColumnType("int");

                    b.HasKey("ser_id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Hair_Salon_Web_ASP.NET.Models.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ConfirmPassword")
                        .HasColumnType("longtext");

                    b.Property<string>("about_user")
                        .HasColumnType("longtext");

                    b.Property<string>("address")
                        .HasColumnType("longtext");

                    b.Property<string>("gender")
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("role")
                        .HasColumnType("longtext");

                    b.HasKey("user_id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Hair_Salon_Web_ASP.NET.Models.Appointment", b =>
                {
                    b.HasOne("Hair_Salon_Web_ASP.NET.Models.User", "user")
                        .WithMany("appointment")
                        .HasForeignKey("emp_id_chosen")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hair_Salon_Web_ASP.NET.Models.Service", "service")
                        .WithMany("appointment")
                        .HasForeignKey("ser_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("service");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Hair_Salon_Web_ASP.NET.Models.Service", b =>
                {
                    b.Navigation("appointment");
                });

            modelBuilder.Entity("Hair_Salon_Web_ASP.NET.Models.User", b =>
                {
                    b.Navigation("appointment");
                });
#pragma warning restore 612, 618
        }
    }
}
